"""Generate docs from the registry and the freshly generated data (run after `make data`):

    docs/AGENT_CATALOG.md  — from backend/app/agents/registry.py
    docs/DEMO_SCRIPT.md    — Section 11 script with the actual numbers of the generated tenants
    data_gen/README.md     — tables, volumes and planted anomalies with counts per tenant
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "backend"), str(ROOT)]

from app.agents.registry import catalog_markdown  # noqa: E402
from app.config import demo_today  # noqa: E402
from app.db import models  # noqa: E402
from app.db.session import Repo  # noqa: E402
from app.services.metrics import dashboard, latest_output  # noqa: E402


def months(days: int) -> int:
    return round(days / 30.4)


def facts(t: str) -> dict:
    r = Repo(t)
    out = {}
    d = latest_output(r, "pf.app_discovery")
    nf = [f for f in d["findings"] if f["type"] == "new_app"]
    out["shadow"] = len(nf)
    out["shadow_genai_expense"] = sum(1 for f in nf if f.get("genai") and f.get("paid_via_expense"))
    out["genai_names"] = [f["candidate_name"] for f in nf if f.get("genai")]
    out["retired_candidates"] = [g["canonical"] for g in r.all("gt_shadow_it") if g["truth"] == "retired"]
    out["cmdb_dup"] = sum(1 for f in d["findings"] if f["type"] == "cmdb_duplicate")
    out["cmdb_stale"] = sum(1 for f in d["findings"] if f["type"] == "cmdb_stale")
    out["expense_ref"] = (d["findings"] and next((f["source_refs"][0]["record_id"] for f in nf if f.get("paid_via_expense")), ""))
    lc = latest_output(r, "pf.lifecycle_watcher")
    eos = [f for f in lc["findings"] if f["type"] == "vendor_eos"]
    out["eos"] = eos
    traps = [f for f in lc["findings"] if f["type"] == "contract_renewal" and f.get("auto_renew") and (f.get("utilization") or 1) < 0.3]
    out["traps"] = traps
    ov = latest_output(r, "pf.overlap_finder")
    out["overlaps"] = ov["findings"]
    rk = latest_output(r, "dai.ai_risk_classifier")
    out["tiers"] = {f["title"]: f["tier"] for f in rk["findings"]}
    out["tier_counts"] = Counter(f["tier"] for f in rk["findings"])
    reg = latest_output(r, "dai.model_agent_registry_steward")
    out["assets"] = reg["facts"] if "facts" in reg else None
    out["n_assets"] = r.count("ai_assets")
    out["n_unreg"] = sum(1 for a in r.all("ai_assets") if not a["registered"])
    dr = latest_output(r, "app.design_review")
    out["designs"] = {f["title"]: f for f in dr["findings"]}
    dd = latest_output(r, "app.drift_detector")
    out["boundary"] = [f for f in dd["findings"] if f["type"] == "boundary_violation"]
    cost = latest_output(r, "pf.cost_license_optimizer")
    out["cost"] = cost["findings"]
    out["apps"] = {a["name"]: a for a in r.all("applications")}
    out["metrics"] = dashboard(t)
    return out


def demo_script() -> str:
    n, m = facts("northgrid"), facts("meridian")
    trap = next((t for t in n["traps"] if t["name"] == "Vizora Analytics"), n["traps"][0] if n["traps"] else None)
    docs = next((o for o in n["overlaps"] if "TeamSpace Docs" in o["app_names"]), None)
    uis = n["designs"].get("Customer Usage Insights service")
    oms = next((e for e in n["eos"] if e["name"] == "OutageWorks OMS"), None)
    billing = next((o for o in m["overlaps"] if "Coastline Billing (Legacy)" in o["app_names"]), None)
    charge = next((c for c in m["cost"] if c["type"] == "above_market_price"), None)
    sav, roi = n["metrics"]["savings"], n["metrics"]["roi"]
    return f"""# Sales demo script (12 minutes)

*Generated by `make docs` from the synthetic data (seed 42, demo date {demo_today().isoformat()}). Numbers below are what the
UI shows on a fresh `make reset`. UI labels in **bold** match the screens.*

**Setup:** `make demo` → open http://localhost:5173/welcome. Tenant **NorthGrid Energy**, **Acting as** Avery Lindqvist —
Principal Architect, badge **Mock LLM**.

## 0. The pitch (1 min) — /welcome
"An architecture office in a box. Agents find the money and the risk; your people decide; every number has evidence."
Point at the live proof tiles: **{usd(sav['identified'])} savings identified**, **{n['shadow']} shadow IT tools**,
**{roi['multiple']}x return** on the {roi['plan']} plan ({usd(roi['annual_fee_usd'])}/yr). Click **Open live demo**.

## 1. Connect (1 min) — Connected Sources
"Read-only connectors: SSO, invoices and expenses, cloud billing, CMDB, Git, data catalogue, model registry." Open the
**SSO identity provider** and **CMDB** cards to show the messy names (`TEAMSPACE DOCS`, `teamspace-docs-prod`, `NG-…`).

## 2. Find the money (4 min) — SaaS & Cloud Savings
1. **Discovery** → **Re-run** *Application Discovery*: **{n['shadow']} shadow IT tools**, **{n['shadow_genai_expense']} generative-AI tools paid
   through expense reports** ({', '.join(n['genai_names'])}), **{n['cmdb_dup']} CMDB duplicates**, **{n['cmdb_stale']} stale CIs**.
2. Click an evidence chip (e.g. `[{n['expense_ref']}]`) → the raw expense line. "Every number is traceable."
3. **Overlaps**: {len(docs['app_ids']) if docs else 3} document-management tools ({', '.join(docs['app_names']) if docs else ''}),
   survivor **{docs['survivor_name'] if docs else 'TeamSpace Docs'}**, ~{usd(docs['est_savings_usd']) if docs else ''}/yr.
4. **Renewals**: **{trap['name'] if trap else 'Vizora Analytics'}** auto-renews in **{trap['days_remaining'] if trap else '-'} days** at
   **{round((trap['utilization'] or 0) * 100) if trap else '-'}% seat utilisation**; **OutageWorks OMS** end of support in
   **{months(oms['days_remaining']) if oms else 7} months**.
5. **Build business case** on the document cluster → switch **Acting as** to the **CIO** → approve in **Approvals** →
   **Overview** savings *approved* and **Return on subscription** go up.

## 3. Govern AI (3 min) — AI Governance
- **Classify risk** on *Dynamic pricing recommendation* → **{n['tiers'].get('Dynamic pricing recommendation', 'high').upper()}** (AIR-H4) with
  required controls; *Covert employee sentiment monitoring* → **BLOCKED** (AIR-U1).
- Switch to the **Risk Officer** → approve tiers (the architect cannot sign off AI risk — separation of duties).
- **AI asset registry**: **{n['n_assets']} AI assets, {n['n_unreg']} unregistered**.
- **Data privacy** tab: policy violations with owners. **Generate evidence pack** → *State PUC customer data privacy rule*.
  "This is what your auditor asks for."

## 4. Review designs (2 min) — Design Reviews
- Open **Customer Usage Insights service** → **{(uis['verdict'] if uis else 'changes_required').replace('_', ' ')}** with concerns
  {', '.join(c['standard_id'] for c in uis['concerns']) if uis else ''}, and a suggestion to reuse the **Customer Lookup API**.
- **Drift**: **{len(n['boundary'])} IT/OT boundary violations** → approve **create remediation ticket** as **Security Architect** → ticket opened.

## 5. Close (1 min) — Copilot, second tenant, pricing
- **Copilot**: "Which AI assets are unregistered?" then "Who owns them?" — cited answers, follow-ups remembered.
- Switch to **Meridian Telecom**: two billing systems after the merger ({', '.join(billing['app_names']) if billing else ''}),
  charging contract at **2x market** ({charge['evidence'] if charge else ''}), **Next-best-offer** tiered
  **{m['tiers'].get('Next-best-offer', 'high').upper()}**. Same product, different industry.
- Back to **/welcome#pricing**: "Start with the 2-week savings assessment; it's credited against year one."
"""


def usd(v: float) -> str:
    return f"${v / 1e6:.1f}M" if v >= 1e6 else f"${v / 1e3:.0f}k"


def data_readme() -> str:
    from data_gen.generators.core import load_yaml  # noqa: F401

    lines = ["# Synthetic data generator", "", "```", "python -m data_gen.generate --tenant northgrid --seed 42 --out data/northgrid.db",
             "python -m data_gen.generate --tenant meridian --seed 42 --out data/meridian.db", "python -m data_gen.generate --all", "```", "",
             "Deterministic: same seed + same `DEMO_TODAY` → identical data. All dates are relative to `DEMO_TODAY` (default today).",
             "Industry content is hand-authored in `catalogs/utilities.yaml`, `catalogs/telecom.yaml`, `catalogs/common.yaml` and",
             "`catalogs/ai_risk_rules.yaml`; generators in `generators/` add the long tail and the planted anomalies.",
             "Raw per-source exports (`sso.csv`, `invoices.csv`, `cmdb.json`, `cloud.json`, `repos.json`, `catalog.json`, …) are written",
             "to `data/{tenant}/raw/`. After writing the tables the generator builds the knowledge graph and runs every agent once",
             "(baseline, trigger `scheduled`) plus a small set of historical decisions (`backend/app/services/bootstrap.py`).", "",
             "## Tables and volumes", "", "| Table | NorthGrid | Meridian | Notes |", "|---|---|---|---|"]
    notes = {"gt_app_aliases": "hidden ground truth: raw name → application", "gt_shadow_it": "hidden ground truth: shadow IT",
             "gt_planted": "hidden ground truth: every planted anomaly", "kg_nodes": "knowledge graph", "kg_edges": "knowledge graph",
             "agent_runs": "baseline runs", "approvals": "baseline proposals + history", "audit_events": "", "tickets": "simulated Jira"}
    rn, rm = Repo("northgrid"), Repo("meridian")
    for t in models.metadata.tables:
        if t in ("tenants", "meta_kv", "agent_settings"):
            continue
        lines.append(f"| `{t}` | {rn.count(t)} | {rm.count(t)} | {notes.get(t, '')} |")
    lines += ["", "## Planted anomalies (counts)", "", "| Anomaly | NorthGrid | Meridian |", "|---|---|---|"]
    cn = Counter(p["anomaly"] for p in rn.all("gt_planted"))
    cm = Counter(p["anomaly"] for p in rm.all("gt_planted"))
    for k in sorted(set(cn) | set(cm)):
        lines.append(f"| {k.replace('_', ' ')} | {cn.get(k, 0)} | {cm.get(k, 0)} |")
    lines += ["", "Every planted anomaly is listed with its subject record in table `gt_planted` and shown in the UI under",
              "**Ingested Sources → show what we planted**. Tests in `backend/tests/test_planted_anomalies.py` assert the ranges."]
    return "\n".join(lines) + "\n"


def gen_prompts(overwrite: bool = False) -> int:
    """Live-mode prompt per agent: role, inputs, finding schema, rules (+ shared rules from _common.md)."""
    import json

    from app.agents.registry import AGENTS

    pdir = ROOT / "backend" / "app" / "llm" / "prompts"
    common = (pdir / "_common.md").read_text()
    n = 0
    for a in AGENTS.values():
        path = pdir / f"{a.id}.md"
        if not a.runnable or (path.exists() and not overwrite):
            continue
        props = {k: v.get("type", v.get("anyOf", "")) for k, v in a.finding_model.model_json_schema().get("properties", {}).items()}
        path.write_text(
            f"# {a.name} (`{a.id}`)\n\n## Role\n{a.description}\n\n## Inputs\nTables read by the tool layer: {', '.join(a.inputs)}. "
            f"The user message contains the tool results as JSON: `facts` and `findings` (typed `{a.outputs}`, each with `source_refs`).\n\n"
            f"## Finding schema (already computed — do not change values)\n```json\n{json.dumps(props, indent=1, default=str)}\n```\n\n"
            f"## What to write\n- A summary a {a.approver_role or 'principal architect'} can act on, leading with the most material finding.\n"
            f"- Rank findings by business impact (risk, money, deadline) in `order`.\n"
            f"- Optionally add up to 5 `notes`, each citing that finding's record ids.\n"
            f"- Proposed actions ({', '.join(a.action_types) or 'none'}) are created by the platform; never claim anything is approved.\n\n{common}")
        n += 1
    return n


def main() -> None:
    gen_prompts()
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "AGENT_CATALOG.md").write_text(catalog_markdown())
    (ROOT / "docs" / "DEMO_SCRIPT.md").write_text(demo_script())
    (ROOT / "data_gen" / "README.md").write_text(data_readme())
    print("wrote docs/AGENT_CATALOG.md, docs/DEMO_SCRIPT.md, data_gen/README.md")


if __name__ == "__main__":
    main()
